version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "src/package.json" }}
          - v1-dependencies-
      - run: cd src && yarn install
      - save_cache:
          paths:
            - src/node_modules
          key: v1-dependencies-{{ checksum "src/package.json" }}
      - run: cd src && yarn test
