version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:9-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "src/package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - src/node_modules
          key: v1-dependencies-{{ checksum "src/package.json" }}
      - run: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
